name: Deployment
on:
  push:
    branches:
      - "main"
jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapi:latest
  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    needs: build_docker_image
    env:
      HEROKU_APP: "simple-api-berv"
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.HEROKU_APP}}
          heroku_email: "bervianto.leo@gmail.com"
          stack: container
          justlogin: true
      - name: Re-TAG
        run : |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapi:latest
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/simpleapi:latest registry.heroku.com/${{env.HEROKU_APP}}/web
      - name: Push to heroku registry
        run: docker push registry.heroku.com/${{env.HEROKU_APP}}/web


